CREATE DATABASE CARPARKING;

CREATE TABLE PARKING_SLOTS(
	slot_id INT PRIMARY KEY NOT NULL,
    vacant BINARY NOT NULL,
    p_time TIME
);

CREATE TABLE PRICES(
	duration DOUBLE PRIMARY KEY NOT NULL,
    price DOUBLE NOT NULL
);